// ----------------------------------------------------------------------

export const countries = [
  { code: "US", label: "United States", phone: "1" },
  { code: "CA", label: "Canada", phone: "1" },
  { code: "GB", label: "United Kingdom", phone: "44" },
  { code: "DE", label: "Germany", phone: "49" },
  { code: "FR", label: "France", phone: "33" },
  { code: "IT", label: "Italy", phone: "39" },
  { code: "ES", label: "Spain", phone: "34" },
  { code: "NL", label: "Netherlands", phone: "31" },
  { code: "BE", label: "Belgium", phone: "32" },
  { code: "CH", label: "Switzerland", phone: "41" },
  { code: "AT", label: "Austria", phone: "43" },
  { code: "SE", label: "Sweden", phone: "46" },
  { code: "NO", label: "Norway", phone: "47" },
  { code: "DK", label: "Denmark", phone: "45" },
  { code: "FI", label: "Finland", phone: "358" },
  { code: "PL", label: "Poland", phone: "48" },
  { code: "CZ", label: "Czech Republic", phone: "420" },
  { code: "HU", label: "Hungary", phone: "36" },
  { code: "RO", label: "Romania", phone: "40" },
  { code: "BG", label: "Bulgaria", phone: "359" },
  { code: "HR", label: "Croatia", phone: "385" },
  { code: "SI", label: "Slovenia", phone: "386" },
  { code: "SK", label: "Slovakia", phone: "421" },
  { code: "LT", label: "Lithuania", phone: "370" },
  { code: "LV", label: "Latvia", phone: "371" },
  { code: "EE", label: "Estonia", phone: "372" },
  { code: "IE", label: "Ireland", phone: "353" },
  { code: "PT", label: "Portugal", phone: "351" },
  { code: "GR", label: "Greece", phone: "30" },
  { code: "CY", label: "Cyprus", phone: "357" },
  { code: "MT", label: "Malta", phone: "356" },
  { code: "LU", label: "Luxembourg", phone: "352" },
  { code: "IS", label: "Iceland", phone: "354" },
  { code: "LI", label: "Liechtenstein", phone: "423" },
  { code: "MC", label: "Monaco", phone: "377" },
  { code: "SM", label: "San Marino", phone: "378" },
  { code: "VA", label: "Vatican City", phone: "379" },
  { code: "AD", label: "Andorra", phone: "376" },
  { code: "AU", label: "Australia", phone: "61" },
  { code: "NZ", label: "New Zealand", phone: "64" },
  { code: "JP", label: "Japan", phone: "81" },
  { code: "KR", label: "South Korea", phone: "82" },
  { code: "CN", label: "China", phone: "86" },
  { code: "IN", label: "India", phone: "91" },
  { code: "BR", label: "Brazil", phone: "55" },
  { code: "AR", label: "Argentina", phone: "54" },
  { code: "MX", label: "Mexico", phone: "52" },
  { code: "CL", label: "Chile", phone: "56" },
  { code: "CO", label: "Colombia", phone: "57" },
  { code: "PE", label: "Peru", phone: "51" },
  { code: "VE", label: "Venezuela", phone: "58" },
  { code: "EC", label: "Ecuador", phone: "593" },
  { code: "BO", label: "Bolivia", phone: "591" },
  { code: "PY", label: "Paraguay", phone: "595" },
  { code: "UY", label: "Uruguay", phone: "598" },
  { code: "GY", label: "Guyana", phone: "592" },
  { code: "SR", label: "Suriname", phone: "597" },
  { code: "FK", label: "Falkland Islands", phone: "500" },
  { code: "GF", label: "French Guiana", phone: "594" },
  { code: "ZA", label: "South Africa", phone: "27" },
  { code: "EG", label: "Egypt", phone: "20" },
  { code: "NG", label: "Nigeria", phone: "234" },
  { code: "KE", label: "Kenya", phone: "254" },
  { code: "ET", label: "Ethiopia", phone: "251" },
  { code: "TZ", label: "Tanzania", phone: "255" },
  { code: "UG", label: "Uganda", phone: "256" },
  { code: "GH", label: "Ghana", phone: "233" },
  { code: "CI", label: "Ivory Coast", phone: "225" },
  { code: "SN", label: "Senegal", phone: "221" },
  { code: "ML", label: "Mali", phone: "223" },
  { code: "BF", label: "Burkina Faso", phone: "226" },
  { code: "NE", label: "Niger", phone: "227" },
  { code: "TD", label: "Chad", phone: "235" },
  { code: "SD", label: "Sudan", phone: "249" },
  { code: "LY", label: "Libya", phone: "218" },
  { code: "TN", label: "Tunisia", phone: "216" },
  { code: "DZ", label: "Algeria", phone: "213" },
  { code: "MA", label: "Morocco", phone: "212" },
  { code: "CM", label: "Cameroon", phone: "237" },
  { code: "CF", label: "Central African Republic", phone: "236" },
  { code: "CG", label: "Republic of the Congo", phone: "242" },
  { code: "CD", label: "Democratic Republic of the Congo", phone: "243" },
  { code: "GA", label: "Gabon", phone: "241" },
  { code: "GQ", label: "Equatorial Guinea", phone: "240" },
  { code: "ST", label: "São Tomé and Príncipe", phone: "239" },
  { code: "GW", label: "Guinea-Bissau", phone: "245" },
  { code: "GN", label: "Guinea", phone: "224" },
  { code: "SL", label: "Sierra Leone", phone: "232" },
  { code: "LR", label: "Liberia", phone: "231" },
  { code: "TG", label: "Togo", phone: "228" },
  { code: "BJ", label: "Benin", phone: "229" },
  { code: "CV", label: "Cape Verde", phone: "238" },
  { code: "GM", label: "Gambia", phone: "220" },
  { code: "MR", label: "Mauritania", phone: "222" },
  { code: "EH", label: "Western Sahara", phone: "212" },
  { code: "AO", label: "Angola", phone: "244" },
  { code: "NA", label: "Namibia", phone: "264" },
  { code: "BW", label: "Botswana", phone: "267" },
  { code: "ZW", label: "Zimbabwe", phone: "263" },
  { code: "ZM", label: "Zambia", phone: "260" },
  { code: "MW", label: "Malawi", phone: "265" },
  { code: "MZ", label: "Mozambique", phone: "258" },
  { code: "MG", label: "Madagascar", phone: "261" },
  { code: "MU", label: "Mauritius", phone: "230" },
  { code: "SC", label: "Seychelles", phone: "248" },
  { code: "KM", label: "Comoros", phone: "269" },
  { code: "DJ", label: "Djibouti", phone: "253" },
  { code: "SO", label: "Somalia", phone: "252" },
  { code: "ER", label: "Eritrea", phone: "291" },
  { code: "RW", label: "Rwanda", phone: "250" },
  { code: "BI", label: "Burundi", phone: "257" },
  { code: "SS", label: "South Sudan", phone: "211" },
];
